config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'profile', to: 'users#profile'

  root to: 'pages#home'
  get 'start', to: 'pages#start', as: :start
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'my_box', to: 'pages#my_box', as: :my_box
  get 'my_addresses', to: 'pages#my_addresses', as: :my_addresses
  get 'cancel', to: 'pages#cancel', as: :cancel

  post 'fetch_address', to: 'ceps#fetch_address', as: :fetch_address
  post 'calculate_shipment', to: 'ceps#calculate_shipment', as: :calculate_shipment

  resources :plans, only: %i[new create show destroy update], shallow: true do
    member do
      patch '/update', to: 'plans#update_my_box'
      patch '/cancel_box', to: 'plans#cancel_box'
    end
  end
  post :shopcart, to: 'plans#shopcart'

  resources :orders, only: %i[show create] do
    member do
      get 'confirm_payment', to: 'orders#confirm_payment', as: :confirm_payment
    end
    resources :payments, only: :new
  end
  resources :carrefour_boxes, only: %i[create show update destroy] do
    resources :reviews, only: %i[create update destroy], shallow: true
  end

  resources :box_items, only: %i[new create destroy]
  resources :addresses, only: %i[create update destroy] do
    collection do
      patch 'choose', to: 'addresses#address_choice'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plans, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :boxes, through: :plans
  has_many :box_items, through: :boxes
  has_many :orders
  has_many :reviews, dependent: :destroy

  # validations
  validates :first_name, :last_name, :birth_date, :cpf, :phone, presence: true, unless: :admin?
  validates :password, format: { with: /(.*([A-Za-z]+[0-9]|[0-9]+[A-Za-z]).*)/ }, unless: -> { password.blank? } 
  validates :cpf, uniqueness: true, format: { with: /\A(\d{11}|\d{3}\.\d{3}\.\d{3}-\d{2})\z/ }

  attr_writer :login

  def login
    @login || cpf || email
  end

  def name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(cpf) = :value OR lower(email) = :value', { value: login.downcase }]).first
    elsif conditions.key?(:cpf) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  def main_address
    addresses.active.where(main: true).first
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  respond_to :html, :js
  prepend_before_action :require_no_authentication, only: [:new]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end
  
  # POST /resource/sign_in
  def create
    respond_to do |format|
      if warden.authenticate(auth_options).nil?
        format.turbo_stream do
          flash.now[:alert] = 'Credenciais inválidas'
          render turbo_stream: turbo_stream.replace(:alerts, partial: 'shared/flashes')
        end
      else
        format.html { super }
      end
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
    skip_authorization
  end
end

app/views/users/profile.html.erb
<% content_for(:page_header, 'Meu perfil') %>

<div class="container">
  <div class='avatar-container my-3'>
    <%= image_tag 'profile', class: 'avatar' %>
    <%= link_to "#", class: 'f-center' do %>
      <i aria-hidden="true" class="far fa-edit"></i>
    <% end %>
  </div>

  <div class='profile-header my-4'>
    <h3><%= current_user.name %></h3>
    <%= link_to 'Editar perfil', edit_user_registration_path %>
  </div>

  <ul class='profile-list-links'>
    <div>
      <li>
        <%= link_to "#" do %>
          <i aria-hidden="true" class="fas fa-ticket-alt"></i>
          <div>
            <p>Meus cupons</p>
            <span>Todos os Cupons de descontos ativos</span>
          </div>
          <i aria-hidden="true" class="fas fa-chevron-right"></i>
        <% end %>
      </li>
      <li>
        <%= link_to "#" do %>
          <i aria-hidden="true" class="fas fa-scroll"></i>
          <div>
            <p>Pedidos e compras</p>
            <span>Histórico de compras e compras ativas</span>
          </div>
          <i aria-hidden="true" class="fas fa-chevron-right"></i>
        <% end %>
      </li>
      <li>
        <% if current_user.plans.joins(:orders).where(orders: { status: "complete" }).empty? %>
          <%= link_to new_plan_path do %>
            <i aria-hidden="true" class="fas fa-box-open"></i>
            <div>
              <p>BOX Carrefour</p>
              <span>Adquira sua BOX!</span>
            </div>
            <i aria-hidden="true" class="fas fa-chevron-right"></i>
          <% end %>
        <% else %>
          <%= link_to my_box_path do %>
            <i aria-hidden="true" class="fas fa-box-open"></i>
            <div>
              <p>BOX Carrefour</p>
              <span>Seu plano ativo</span>
            </div>
            <i aria-hidden="true" class="fas fa-chevron-right"></i>
          <% end %>
        <% end %>
      </li>
      <li>
        <%= link_to my_addresses_path do %>
          <i aria-hidden="true" class="fas fa-map-marker-alt"></i>
          <div>
            <p>Meus endereços</p>
            <span>Endereços cadastrados e de entrega</span>
          </div>
          <i aria-hidden="true" class="fas fa-chevron-right"></i>
        <% end %>
      </li>
      <li>
        <%= link_to "#" do %>
          <i aria-hidden="true" class="far fa-comments"></i>
          <div>
            <p>Sua opnião sobre o App</p>
            <span>Conte para nós o que você pensa</span>
          </div>
          <i aria-hidden="true" class="fas fa-chevron-right"></i>
        <% end %>
      </li>
    </div>
    <div>
      <li>
        <%= link_to "#" do %>
          <i aria-hidden="true" class="far fa-question-circle"></i>
          <p>Central de ajuda</p>
        <% end %>
      </li>
      <li>
        <%= link_to "#" do %>
          <i aria-hidden="true" class="fas fa-book-open"></i>
          <p>Manual do SuperApp</p>
        <% end %>
      </li>
    </div>
    <div class='app-options'>
      <li><%= link_to 'Termos e Condições', '#' %></li>
      <li><%= link_to 'Política de Privacidade', '#' %></li>
      <li><%= link_to 'Avalie o App', '#' %></li>
      <li><%= link_to 'Sobre o App', '#' %></li>
      <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
    </div>
    <span>Versão do app XX.X.X</span>
  </ul>
</div>