config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'profile', to: 'users#profile'

  root to: 'pages#home'
  get 'start', to: 'pages#start', as: :start
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'my_box', to: 'pages#my_box', as: :my_box
  get 'my_addresses', to: 'pages#my_addresses', as: :my_addresses
  get 'cancel', to: 'pages#cancel', as: :cancel

  post 'fetch_address', to: 'ceps#fetch_address', as: :fetch_address
  post 'calculate_shipment', to: 'ceps#calculate_shipment', as: :calculate_shipment

  resources :plans, only: %i[new create show destroy update], shallow: true do
    member do
      patch '/update', to: 'plans#update_my_box'
      patch '/cancel_box', to: 'plans#cancel_box'
    end
  end
  post :shopcart, to: 'plans#shopcart'

  resources :orders, only: %i[show create] do
    member do
      get 'confirm_payment', to: 'orders#confirm_payment', as: :confirm_payment
    end
    resources :payments, only: :new
  end
  resources :carrefour_boxes, only: %i[create show update destroy] do
    resources :reviews, only: %i[create update destroy], shallow: true
  end

  resources :box_items, only: %i[new create destroy]
  resources :addresses, only: %i[create update destroy] do
    collection do
      patch 'choose', to: 'addresses#address_choice'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  include SoftDeletable

  belongs_to :user

  geocoded_by :full_address
  after_validation :geocode
  before_validation :generate_full_addresss

  validates :name, :cep, :street, :number, :state, :city, :full_address, presence: true
  validates :main, inclusion: { in: [true, false] }

  private

  def generate_full_addresss
    self.full_address = "#{street}, #{number}, #{city}, #{state}"
  end
end

app/models/box.rb
class Box < ApplicationRecord
  BOX_SIZES = %w[P M G].freeze

  belongs_to :plan
  belongs_to :box_item

  validates :box_size, inclusion: { in: BOX_SIZES }
end

app/models/box_item.rb
class BoxItem < ApplicationRecord
  belongs_to :carrefour_box
  has_many :boxes, dependent: :destroy

  validates :name, presence: true
end

app/models/box_name.rb
class BoxName < ApplicationRecord
  validates :name, :description, :color, presence: true
  validates :name, uniqueness: true

  has_one_attached :icon
end

app/models/carrefour_box.rb
class CarrefourBox < ApplicationRecord
  has_many :box_items, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :icon

  validates :name, :description, :color, presence: true
  validates :name, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :plan

  monetize :amount_cents

  validates :status, inclusion: { in: %w[pending complete canceled] }
end

app/models/plan.rb
class Plan < ApplicationRecord
  SHIP_DAYS = [10, 20, 30].freeze

  belongs_to :user
  belongs_to :address
  has_many :boxes, dependent: :destroy
  has_many :box_items, through: :boxes
  has_many :carrefour_boxes, through: :box_items
  has_many :shipments, dependent: :destroy
  has_many :orders, dependent: :destroy

  before_validation :set_ship_day

  monetize :price_cents, as: :price
  monetize :shipment_cents, as: :shipment
  monetize :total_price_cents, as: :total_price

  validates :quantity, :total_price_cents, :price_cents, :shipment_cents,
            numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
  validates :carrefour_card, :active, inclusion: { in: [true, false] }

  def self.discount_hash
    { 2 => 0.05, 3 => 0.1 }.freeze
  end

  def self.discounts(num)
    Plan.discount_hash.keys.include?(num) ? (1 - Plan.discount_hash[num]) : 1
  end

  def calculate_total
    shipping = calculate_shipment
    subscription = calculate_subscription
    update(
      price_cents: subscription,
      shipment_cents: shipping,
      total_price_cents: subscription + shipping
    )
  end

  def calculate_shipment
    if carrefour_card
      0
    else
      shipment_distance = Geocoder::Calculations.distance_between(CARREFOUR_COORDS, address)
      shipment_distance < 100 ? 1499 : 1499 + shipment_distance.round
    end
  end

  private

  def calculate_subscription
    subscription = 0
    boxes.includes(box_item: :carrefour_box).group_by { |box| box.box_item.carrefour_box }.each do |box, items|
      subscription += box.plans[items.first.box_size]['price']
    end
    subscription * Plan.discounts(quantity)
  end

  def set_ship_day
    day = created_at ? created_at.day : Time.now.day
    self.ship_day = if day >= 6 && day <= 15
                      20
                    elsif day >= 16 && day <= 25
                      30
                    else
                      10
                    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :carrefour_box

  after_create :update_carrefour_box_rating
  before_destroy :update_carrefour_box_rating_destroy

  validates :rating, presence: true, inclusion: { in: (1..5).to_a }, numericality: { only_integer: true }

  private

  def update_carrefour_box_rating
    reviews = carrefour_box.reviews
    new_rating = reviews.reduce(0.0) do |total, review|
      review.rating + total
    end.to_f / reviews.size
    carrefour_box.update(average_rating: new_rating.round(1))
  end

  def update_carrefour_box_rating_destroy
    reviews = carrefour_box.reviews.where.not(id: id)
    new_rating = reviews.reduce(0.0) do |total, review|
      review.rating + total
    end.to_f / reviews.size
    carrefour_box.update(average_rating: new_rating.round(1))
  end
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  include ShippingCodeGenerator

  belongs_to :plan

  before_create :assign_shipping_code

  monetize :shipping_cost_cents, as: :shipping_cost

  validates :shipping_cost_cents, numericality: { greater_than_or_equal_to: 0 }

  private

  def assign_shipping_code
    self.shipping_code = generate_code
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plans, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :boxes, through: :plans
  has_many :box_items, through: :boxes
  has_many :orders
  has_many :reviews, dependent: :destroy

  # validations
  validates :first_name, :last_name, :birth_date, :cpf, :phone, presence: true, unless: :admin?
  validates :password, format: { with: /(.*([A-Za-z]+[0-9]|[0-9]+[A-Za-z]).*)/ }, unless: -> { password.blank? } 
  validates :cpf, uniqueness: true, format: { with: /\A(\d{11}|\d{3}\.\d{3}\.\d{3}-\d{2})\z/ }

  attr_writer :login

  def login
    @login || cpf || email
  end

  def name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(cpf) = :value OR lower(email) = :value', { value: login.downcase }]).first
    elsif conditions.key?(:cpf) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  def main_address
    addresses.active.where(main: true).first
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/box_form_helper.rb
module BoxFormHelper
  def box_input_value(value)
    if value.nil?
      nil
    elsif value.to_s.size <= 2
      value.to_s
    else
      value.to_s.insert(-3, ',')
    end
  end
end

app/helpers/box_items_helper.rb
module BoxItemsHelper
end

app/helpers/box_names_helper.rb
module BoxNamesHelper
end

app/helpers/ceps_helper.rb
module CepsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/infos/_cancel_terms.html.erb
<div class="start-container", style="font-size: 5px;">
  <h1 class="text-center">Termo de Cancelamento – Assinatura Box Surpresa</h1>
  <div class="text-justify">
    <% if current_user %>
      <p style="font-size: small;"><%= "Eu, #{current_user.name}, portador do CPF nº #{current_user.cpf}, solicito o cancelamento da assinatura do meu Box e declaro estar ciente dos termos abaixo: "%></p>
    <% else %>
      <p style="font-size: small;">"Eu, usuário, solicito o cancelamento da assinatura do meu Box e declaro estar ciente dos termos abaixo: "</p>
    <% end %>
      <li style="font-size: small;">A assinatura será cancelada à partir do momento da confirmação do serviço neste aplicativo, Meu Carrefour (Box Surpresa);</li>
      <li style="font-size: small;">A mensalidade debitada no cartão será automaticamente cancelada;</li>
      <li style="font-size: small;">Para que a cobrança do mês vigente NÃO seja realizada, é necessário o cancelamento por parte do usuário dos serviços do Box Surpresa com 10(dez) dias de antecedência do envio do produto, conforme seu plano personalizado. Caso não seja realizado nos termos em questão, o cancelamento dos serviços e pagamento serão realizados no próximo mês vigente;</li>
      <li style="font-size: small;">Não existe nenhuma cobrança adicional para realização do cancelamento da assinatura;</li>
      <li style="font-size: small;">Uma nova contratação de assinatura de Box poderá ser realizada novamente a qualquer momento pelo usuário.</li>
    </ul>
  </div>
</div>

app/views/infos/_como_funciona.html.erb
<div class="info-container">
  <h2>Como funciona?</h2>
  <p>Escolha: um ou mais BOX com tamanhos  e categorias que te agradem. Lembre-se que o valor dos itens serão superior ao valor pago.</p>
  <p>Descreva: nos informe quais são suas preferências para que possamos personalizar seu BOX baseando-se no seu gosto.</p>
  <p>Receba em casa: chegou a hora tão esperada, receber seu BOX em casa e desfrutar do conteúdo.</p>
</div>

app/views/infos/_o_que_e.html.erb
<div class="info-container">
  <h2>O que é o BOX Surpresa?</h2>
  <p>BOX Surpresa é um programa personalizado de assinatura de diferentes categorias. Possui produtos exclusivos e selecionados de acordo com o seu perfil, trazendo comodidade e facilidade para a sua vida. </p>
</div>

app/views/infos/_o_que_recebe.html.erb
<div class="info-container">
  <h2>O que você recebe?</h2>
  <p>A cada caixa você tem uma experiencia surpreendente. Abaixo contamos um pouco mais pra você de cada categoria:</p>
  <p><b>BOX Happy Hour:</b> bebidas como cerveja, vinho, destilados, sucos e refrigerante. Além de saborosos aperitivos.</p>
  <p><b>BOX Beleza e Cuidado:</b> produtos para cuidados do rosto e corpo como hidratantes, esfoliantes e óleos. Além de produtos  para o cabelo e de esmaltaria.</p>
  <p><b>BOX Receita Certa:</b> ingredientes para que você possa realizar em sua residência os pratos tipicos de Chef.</p>
</div>

app/views/infos/_user_terms.html.erb
<div class="start-container">
  <small>
  <h1 class="text-center">Termo de Adesão – Assinatura Box Surpresa</h1>
  <div class="text-justify">
    <% if current_user %>
      <p style="font-size: 10px;"><%= "Eu, #{current_user.name}, inscrito no CPF/MF sob o nº: #{current_user.cpf}, contratante do serviço de assinatura do Box Surpresa, autorizo a cobrança do(s) produto(s) eserviço(s) adquirido(s), diretamente em minha fatura do cartão cadastrado evalidado pelo assinante no momento da contratação.A vigência desse plano será iniciada no momento da adesão de um ou mais Box,logo após a confirmação de contratação dos serviços dentro do aplicativo MeuCarrefour (Box Surpresa). O presente contrato de assinatura tem por objetivo garantir ao assinante o recebimento mensal de um ou mais Box(s), contratados através do aplicativo MeuCarrefour (Box Surpresa) podendo ser cancelado (parcialmente ou totalmente) à qualquer momento pelo assinante, na área de cancelamento deste aplicativo. São   elegíveis   às   condições   especiais   para   descontos   nas   assinaturas:"%></p>
    <% else %>
      <p style="font-size: 10px;">"Eu, usuário, contratante do serviço de assinatura do Box Surpresa, autorizo a cobrança do(s) produto(s) eserviço(s) adquirido(s), diretamente em minha fatura do cartão cadastrado evalidado pelo assinante no momento da contratação.A vigência desse plano será iniciada no momento da adesão de um ou mais Box,logo após a confirmação de contratação dos serviços dentro do aplicativo MeuCarrefour (Box Surpresa). O presente contrato de assinatura tem por objetivo garantir ao assinante o recebimento mensal de um ou mais Box(s), contratados através do aplicativo MeuCarrefour (Box Surpresa) podendo ser cancelado (parcialmente ou totalmente) à qualquer momento pelo assinante, na área de cancelamento deste aplicativo. São   elegíveis   às   condições   especiais   para   descontos   nas   assinaturas:"</p>
    <% end %>
    <ul>
      <li style="font-size: 10px;">Assinantes de mais de um Box de produtos, tendo desconto mensal de 5% novalor total da contratação para cada Box adicionado, limitando-se ao desconto totalde 10% nas assinaturas (Ex: 02 Boxes 05% e 03 Boxes 10% no total do contrato);</li>
      <li style="font-size: 10px;">Usuários do cartão Carrefour possuem a vantagem de Frete Grátis para recebimento de um ou mais Box.</li>
    </ul>
    <p style="font-size: 8px;">Obs.: As condições especiais possuem caráter cumulativo, podendo chegar à 10% de desconto na assinatura com Frete Grátis.</p>
  </div>
</div>

app/views/infos/_vantagens.html.erb
<div class="info-container">
  <h2>Mais vantagens?</h2>
  <p>Adquirindo mais de um BOX, você ganha 5% de desconto no 2º BOX e 10% de desconto no 3º BOX.</p>
  <p>Usando o cartão Carrefour você ganha ainda mais:</p>
  <p>Frete grátis!</p>
</div>

app/views/layouts/_base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carrefour BOX</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <div id="page-container" class='<%= 'devise' if devise_controller? %>'>
      <%= render 'shared/navbar' unless current_page? root_path %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<%= render 'layouts/base' do %>
  <div id="content-wrap" class='<%= 'home' if current_page? root_path %>'>
    <%= yield %>
  </div>
  <%= render 'shared/menu' %>
<% end %>

app/views/layouts/devise.html.erb
<%= render 'layouts/base' do %>
  <div id="content-wrap">
    <%= yield %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<div id="alerts">
  <% if notice %>
    <div class="alert info fade show" data-controller="alert" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert warning fade show" data-controller="alert" role="alert">
      <%= alert %>
    </div>
  <% end %>
</div>

app/views/shared/_menu.html.erb
<div class='menu-nav' role="menubar" data-controller='modal'>
  <div>
    <%= link_to root_path, aria: { selected: current_page?(root_path)  } do %>
      <i class="fas fa-home" aria-hidden='true'></i>
      <span>Início</span>
    <% end %>
    <%= link_to '#', aria: { selected: false } do %>
      <i class="fas fa-cart-plus" aria-hidden='true'></i>
      <span>Comprar</span>
    <% end %>
    <%= link_to '#', aria: { selected: false } do %>
      <%= inline_svg_tag 'icons/barcode.svg', aria: { hidden: 'true' } %>
      <span>Leitor</span>
    <% end %>
    <%= link_to user_signed_in? ? profile_path : new_user_session_path, aria: { selected: current_page?(profile_path) }, data: user_signed_in? ? {} : { 'bs-toggle': 'modal', 'bs-target': '#sessionModal' }, id: 'sign-in-link' do %>
      <i class="far fa-user" aria-hidden='true'></i>
      <span>Perfil</span>
    <% end %>
    <%= link_to '#', aria: { selected: false } do %>
      <i class="fas fa-ellipsis-h" aria-hidden='true'></i>
      <span>Tudo</span>
    <% end %>
  </div>
</div>

<% if !user_signed_in? %>
  <div class="modal" id="sessionModal" tabindex="-1" aria-labelledby="sessionHeaders" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-body">
          <%= render 'devise/sessions/new' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div id='nav'>
  <div>
    <%= link_to :back do %>
      <%= inline_svg_tag 'icons/arrow.svg' %>
      <p class="visibility-hidden">Voltar a página anterior</p>
    <% end %>
    <h3><%= content_for(:page_header) || "Box Surpresa" %></h3>
  </div>
  <% if controller_name == 'plans' || request.path == start_path %>
    <div class='nav-options'>
      <button type='button' class='menu-btn' data-bs-toggle="collapse" data-bs-target="#navOptions" aria-controls="navOptions" aria-expanded="false" aria-label="Abrir/Fechar menu de opções box surpresa">
        <%= inline_svg_tag 'icons/hamburger.svg' %>
        <p class="visibility-hidden">Menu de opções box surpresa</p>
      </button>
      <% if session["boxes"] %>
        <%= link_to new_plan_path(anchor: session["boxes"].values.select { |box_values| box_values.has_key?("items") && box_values["items"].blank? }.any? ? 'select-items' : 'select-category'),
                    class: "shopcart",
                    id: 'shopcart-link',
                    data: { 'boxes-selected': session["boxes"] ? session["boxes"].keys.count : "" } do %>
          <%= inline_svg_tag 'icons/cart.svg', aria: { hidden: true } %>
          <p class="visibility-hidden">Carrinho de compras</p>
        <% end %>
      <% end %>
    </div>

    <div id='navOptions' class='nav-menu collapse'>
      <div>
        <% if current_user %>
          <% if current_user&.admin %>
            <%= link_to dashboard_path do %>
              <i class="fas fa-truck-loading"></i>
              <p>Administrar caixas</p>
              <i aria-hidden="true" class="fas fa-chevron-right"></i>
            <% end %>
          <% end %>
          <%= link_to my_box_path do %>
            <i class="fas fa-boxes"></i>
            <p>Meu BOX</p>
            <i aria-hidden="true" class="fas fa-chevron-right"></i>
          <% end %>
        <% end %>
        <%= link_to new_plan_path do %>
          <i class="fas fa-store"></i>
          <p>Adquirir nova caixa</p>
          <i aria-hidden="true" class="fas fa-chevron-right"></i>
        <% end %>
        <%= link_to '#', data: { 'bs-toggle': 'offcanvas', 'bs-target': "#oqueCanvas" } do %>
          <i class="fas fa-question"></i>
          <p>O que é?</p>
          <i aria-hidden="true" class="fas fa-chevron-right"></i>
        <% end %>
        <%= link_to '#', data: { 'bs-toggle': 'offcanvas', 'bs-target': "#recebeCanvas" } do %>
          <i class="fas fa-box-open"></i>
          <p>O que você recebe?</p>
          <i aria-hidden="true" class="fas fa-chevron-right"></i>
        <% end %>
        <%= link_to '#', data: { 'bs-toggle': 'offcanvas', 'bs-target': "#comoFuncionaCanvas" } do %>
          <i class="fas fa-info"></i>
          <p>Como funciona?</p>
          <i aria-hidden="true" class="fas fa-chevron-right"></i>
        <% end %>
        <%= link_to '#', data: { 'bs-toggle': 'offcanvas', 'bs-target': "#vantagensCanvas" } do %>
          <i class="fas fa-tags"></i>
          <p>Vantagens</p>
          <i aria-hidden="true" class="fas fa-chevron-right"></i>
        <% end %>
        <%= link_to '#', data: { 'bs-toggle': 'offcanvas', 'bs-target': "#userTermsCanvas" } do %>
          <i class="fas fa-handshake"></i>
          <p>Termo de Adesão</p>
          <i aria-hidden="true" class="fas fa-chevron-right"></i>
        <% end %>
        <%= link_to '#', data: { 'bs-toggle': 'offcanvas', 'bs-target': "#cancelTermsCanvas" } do %>
          <i class="fas fa-window-close"></i>
          <p>Termo de Cancelamento</p>
          <i aria-hidden="true" class="fas fa-chevron-right"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="container offcanvas offcanvas-end" id="oqueCanvas" tabindex="-1" aria-labelledby="sessionHeaders" aria-hidden="true">
  <div class="pt-5 ms-auto">
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <%= render 'infos/o_que_e' %>
</div>

<div class="container offcanvas offcanvas-end" id="recebeCanvas" tabindex="-1" aria-labelledby="sessionHeaders" aria-hidden="true">
  <div class="pt-5 ms-auto">
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <%= render 'infos/o_que_recebe' %>
</div>

<div class="container offcanvas offcanvas-end" id="comoFuncionaCanvas" tabindex="-1" aria-labelledby="sessionHeaders" aria-hidden="true">
  <div class="pt-5 ms-auto">
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <%= render 'infos/como_funciona' %>
</div>

<div class="container offcanvas offcanvas-end" id="vantagensCanvas" tabindex="-1" aria-labelledby="sessionHeaders" aria-hidden="true">
  <div class="pt-5 ms-auto">
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <%= render 'infos/vantagens' %>
</div>

<div class="container offcanvas offcanvas-end" id="cancelTermsCanvas" tabindex="-1" aria-labelledby="sessionHeaders" aria-hidden="true">
  <div class="pt-5 ms-auto">
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <%= render 'infos/cancel_terms' %>
</div>

<div class="container offcanvas offcanvas-end" id="userTermsCanvas" tabindex="-1" aria-labelledby="sessionHeaders" aria-hidden="true">
  <div class="pt-5 ms-auto">
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <%= render 'infos/user_terms' %>
</div>