config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'profile', to: 'users#profile'

  root to: 'pages#home'
  get 'start', to: 'pages#start', as: :start
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'my_box', to: 'pages#my_box', as: :my_box
  get 'my_addresses', to: 'pages#my_addresses', as: :my_addresses
  get 'cancel', to: 'pages#cancel', as: :cancel

  post 'fetch_address', to: 'ceps#fetch_address', as: :fetch_address
  post 'calculate_shipment', to: 'ceps#calculate_shipment', as: :calculate_shipment

  resources :plans, only: %i[new create show destroy update], shallow: true do
    member do
      patch '/update', to: 'plans#update_my_box'
      patch '/cancel_box', to: 'plans#cancel_box'
    end
  end
  post :shopcart, to: 'plans#shopcart'

  resources :orders, only: %i[show create] do
    member do
      get 'confirm_payment', to: 'orders#confirm_payment', as: :confirm_payment
    end
    resources :payments, only: :new
  end
  resources :carrefour_boxes, only: %i[create show update destroy] do
    resources :reviews, only: %i[create update destroy], shallow: true
  end

  resources :box_items, only: %i[new create destroy]
  resources :addresses, only: %i[create update destroy] do
    collection do
      patch 'choose', to: 'addresses#address_choice'
    end
  end
end

app/models/box_item.rb
class BoxItem < ApplicationRecord
  belongs_to :carrefour_box
  has_many :boxes, dependent: :destroy

  validates :name, presence: true
end

app/controllers/box_items_controller.rb
class BoxItemsController < ApplicationController
  def new
    @box_item = BoxItem.new
    authorize @box_item
  end

  def create
    @box_item = BoxItem.new(box_item_params)
    authorize @box_item
    return unless @box_item.save

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.append("box-#{@box_item.carrefour_box.id}-items",
                                                 partial: 'box_items/item',

                                                 locals: { item: @box_item })
      end
    end
  end

  def destroy
    @box_item = BoxItem.find(params[:id])
    authorize @box_item
    @box_item.destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove(@box_item)
      end
    end
  end

  private

  def box_item_params
    params.require(:box_item).permit(:name, :carrefour_box_id)
  end
end

app/helpers/box_items_helper.rb
module BoxItemsHelper
end

app/views/box_items/_item.html.erb
<p id="<%= dom_id item %>">
  <%= link_to box_item_path(item), class: 'me-2', method: :delete, data: { confirm: 'Tem certeza?', turbo: true } do %>
    <i class="fas fa-minus-circle text-danger"></i>
  <% end %>
  <%= item.name %>
</p>

app/views/box_items/new.html.erb
<%= turbo_frame_tag "box-#{params[:carrefour_box_id]}-new-item" do %>
  <div class="pb-3">
    <p class="text-center">Adicionar um novo item:</p>
    <%= form_with(model: @box_item, local: true, html: {class: 'd-flex row row-cols-lg-auto g-3 align-items-center'}, data: { controller: 'form-reset', action: 'turbo:submit-end->form-reset#reset', 'form-reset-target': 'form' }) do %>
      <div class="col-12">
        <div class="input-group justify-content-center">
          <%= hidden_field_tag "box_item[carrefour_box_id]", params[:carrefour_box_id], required: true, class: 'form-control', placeholder: 'nome' %>
          <%= text_field_tag "box_item[name]", @box_item.name, required: true, class: 'form-control', placeholder: 'nome' %>
          <%= submit_tag "Adicionar item", class: 'btn btn-sm btn-dark fs-6' %>
        </div>
      </div>
    </div>
  <% end %>
  <hr>
<% end %>