config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'profile', to: 'users#profile'

  root to: 'pages#home'
  get 'start', to: 'pages#start', as: :start
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'my_box', to: 'pages#my_box', as: :my_box
  get 'my_addresses', to: 'pages#my_addresses', as: :my_addresses
  get 'cancel', to: 'pages#cancel', as: :cancel

  post 'fetch_address', to: 'ceps#fetch_address', as: :fetch_address
  post 'calculate_shipment', to: 'ceps#calculate_shipment', as: :calculate_shipment

  resources :plans, only: %i[new create show destroy update], shallow: true do
    member do
      patch '/update', to: 'plans#update_my_box'
      patch '/cancel_box', to: 'plans#cancel_box'
    end
  end
  post :shopcart, to: 'plans#shopcart'

  resources :orders, only: %i[show create] do
    member do
      get 'confirm_payment', to: 'orders#confirm_payment', as: :confirm_payment
    end
    resources :payments, only: :new
  end
  resources :carrefour_boxes, only: %i[create show update destroy] do
    resources :reviews, only: %i[create update destroy], shallow: true
  end

  resources :box_items, only: %i[new create destroy]
  resources :addresses, only: %i[create update destroy] do
    collection do
      patch 'choose', to: 'addresses#address_choice'
    end
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  SHIP_DAYS = [10, 20, 30].freeze

  belongs_to :user
  belongs_to :address
  has_many :boxes, dependent: :destroy
  has_many :box_items, through: :boxes
  has_many :carrefour_boxes, through: :box_items
  has_many :shipments, dependent: :destroy
  has_many :orders, dependent: :destroy

  before_validation :set_ship_day

  monetize :price_cents, as: :price
  monetize :shipment_cents, as: :shipment
  monetize :total_price_cents, as: :total_price

  validates :quantity, :total_price_cents, :price_cents, :shipment_cents,
            numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
  validates :carrefour_card, :active, inclusion: { in: [true, false] }

  def self.discount_hash
    { 2 => 0.05, 3 => 0.1 }.freeze
  end

  def self.discounts(num)
    Plan.discount_hash.keys.include?(num) ? (1 - Plan.discount_hash[num]) : 1
  end

  def calculate_total
    shipping = calculate_shipment
    subscription = calculate_subscription
    update(
      price_cents: subscription,
      shipment_cents: shipping,
      total_price_cents: subscription + shipping
    )
  end

  def calculate_shipment
    if carrefour_card
      0
    else
      shipment_distance = Geocoder::Calculations.distance_between(CARREFOUR_COORDS, address)
      shipment_distance < 100 ? 1499 : 1499 + shipment_distance.round
    end
  end

  private

  def calculate_subscription
    subscription = 0
    boxes.includes(box_item: :carrefour_box).group_by { |box| box.box_item.carrefour_box }.each do |box, items|
      subscription += box.plans[items.first.box_size]['price']
    end
    subscription * Plan.discounts(quantity)
  end

  def set_ship_day
    day = created_at ? created_at.day : Time.now.day
    self.ship_day = if day >= 6 && day <= 15
                      20
                    elsif day >= 16 && day <= 25
                      30
                    else
                      10
                    end
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new shopcart update]
  before_action :skip_authorization, only: %i[new create update shopcart]
  skip_before_action :verify_authenticity_token, only: [:create]
  before_action :set_plan, only: %i[update destroy update_my_box cancel_box]
  before_action :set_carrefour_box, only: %i[update_my_box cancel_box]

  def new
    @plan = Plan.new
    @carrefour_boxes = CarrefourBox.includes(:box_items).where.not(box_items: { id: nil })
    @boxes = BoxItem.includes(:carrefour_box).group_by(&:carrefour_box)
    @addresses = current_user ? current_user.addresses.active.order(main: :desc) : []
    @address = Address.new
    @current_address = if session[:address_id]
                         Address.find_by(id: session[:address_id])
                       elsif current_user
                         current_user.main_address
                       end
  end

  def shopcart
    boxesInfo = {}
    if params[:carrefour_box]
      params[:carrefour_box].each do |box|
        boxesInfo[box] = { size_price: params[:box_size][box] }
        if params[:box_items] && params[:box_items].has_key?(box)
          boxesInfo[box]['items'] = params[:box_items][box]
        else
          boxesInfo[box].delete('items')
        end
      end
      session['boxes'] = boxesInfo
    else
      session.delete('boxes')
    end
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(:nav, partial: 'shared/navbar')
      end
    end
  end

  def create
    if session['boxes'].blank?
      flash[:notice] = 'Escolha pelo menos uma BOX'
      redirect_to new_plan_path
      return
    elsif session['boxes'].values.any? { |h| h['items'].nil? }
      flash[:notice] = 'Selecione pelo menos um item para todas BOX selecionadas'
      redirect_to new_plan_path(anchor: 'select-items')
      return
    end

    quantity = session['boxes'].keys.count
    @plan = Plan.new(quantity: quantity)
    @plan.user = current_user
    @plan.address = Address.find(params[:address_id])
    return unless @plan.quantity && @plan.save

    current_user.plans.where.not(id: @plan.id).destroy_all

    session['boxes'].each do |k, v|
      create_plan_boxes(@plan, k, v)
    end

    @plan.calculate_total
    flash[:notice] = 'Plano criado!'
    session.delete(:boxes)
    session.delete(:address_id)

    redirect_to @plan
  end

  def show
    @plan = Plan.includes(box_items: :carrefour_box).find(params[:id])
    authorize @plan
    @boxes = @plan.boxes.includes(box_item: [carrefour_box: :reviews]).group_by { |box| box.box_item.carrefour_box }
  end

  def update
    @plan.update(plan_params)
  end

  def destroy
    authorize @plan
    flash[:notice] = 'Plano cancelado!' if @plan.destroy
    redirect_to cancel_path
  end

  def update_my_box
    authorize @plan
    boxes = @plan.boxes.includes(box_item: :carrefour_box).where(box_size: params[:box_size]).where(box_items: { carrefour_box: @carrefour_box })
    destroy_plan_boxes(@plan, @carrefour_box) if boxes.empty?
    update_box_items(@plan, params[:box_size], boxes, params[:items])
    @plan.calculate_total
    redirect_to my_box_path
  end

  def cancel_box
    authorize @plan
    destroy_plan_boxes(@plan, @carrefour_box)
    if @plan.boxes.empty?
      @plan.destroy
    else
      update_quantity(@plan)
      @plan.calculate_total
    end
    redirect_to my_box_path
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def set_carrefour_box
    @carrefour_box = CarrefourBox.find(params[:carrefour_box])
  end

  def create_plan_boxes(plan, box, box_params)
    box_size = CarrefourBox.find(box.to_i).plans.select do |_k, v|
      v['price'] == box_params['size_price'].to_i
    end.keys.first
    box_params['items'].each do |item|
      Box.create(plan: plan, box_item: BoxItem.find(item.to_i), box_size: box_size)
    end
  end

  def update_box_items(plan, box_size, boxes, items)
    boxes.destroy_all

    items.each do |item|
      Box.create(plan: plan, box_size: box_size, box_item: BoxItem.find(item))
    end
  end

  def destroy_plan_boxes(plan, box)
    plan.boxes.includes(box_item: :carrefour_box).where(box_item: { carrefour_box: box }).destroy_all
  end

  def plan_params
    params.require(:plan).permit(:carrefour_card)
  end

  def update_quantity(plan)
    quantity = plan.boxes.includes(box_item: [carrefour_box: :reviews]).group_by do |box|
      box.box_item.carrefour_box
    end.size
    plan.update(quantity: quantity)
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_plan.html.erb
<div class="plan-info pb-3" id="<%= dom_id plan %>">
  <p>Plano: <%= plan.category %></p>
  <p>Valor Mensal: <%= humanized_money_with_symbol plan.monthly_price %></p>
  <p>Valor Total: <%= humanized_money_with_symbol plan.price %></p>
  <p>Data de contratacão: <%= plan.created_at.strftime("%d/%m/%Y") %></p>
  <p>Data de expiração: <%= plan.expires_at.strftime("%d/%m/%Y") %></p>
  <% if plan.shipments.size.positive? %>
    <p>Envios:</p>
    <ul>
      <% plan.shipments.each do |shipment| %>
        <li class="fs-5"><%= shipment.created_at.strftime("%d/%m/%Y")%> - <%= link_to shipment.shipping_code, 'https://www2.correios.com.br/sistemas/rastreamento/' %></li>
      <% end %>
    </ul>
  <% else %>
    <span>Sua primeira caixa será enviada no próximo dia <b><%= plan.ship_day %></b></span>
  <% end %>
  <div class="text-center pb-3 cancel-link">
    <%= link_to 'Cancelar Assinatura', plan_path(plan), method: :delete, class: "text-danger", data: { confirm: 'Tem certeza?'} %>
  </div>
  <div class="text-center pb-3 cancel-link">
    <%= link_to "#{plan.auto_renew ? 'Cancelar' : 'Ativar'} Renovação Automática", toggle_auto_renew_plan_path(plan), method: :put, class: "text-danger", data: { confirm: 'Tem certeza?'} %>
  </div>
</div>

app/views/plans/new.html.erb
<div class="new-plan" data-controller='new-plan'>

  <%= form_with(url: shopcart_path, html: { class: 'f-column', data: { action: 'change->new-plan#submitForm', 'new-plan-target': 'form' } }) do |f| %>
    <div id="select-box" class="tab" data-new-plan-target='tab'>
      <h2>Selecione quais caixas deseja</h2>
      <%= field_set_tag nil, class: 'checkbox-fieldset' do %>
        <% @carrefour_boxes.each do |box| %>
          <%= label_tag "plan_carrefour_box_#{box.id}" do %>
            <%= check_box_tag "carrefour_box[]", box.id, session["boxes"] ? session["boxes"].has_key?(box.id.to_s) : false, id: "plan_carrefour_box_#{box.id}" %>
            <%= cl_image_tag box.icon.key, width: 35, data: { 'color-target': box.color } %>
            <span style="color: <%= box.color %>"><%= box.name %></span>
            <div class="custom-checkbox" style="border-color: <%= box.color %>"></div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div id='select-items' class="tab" data-new-plan-target='tab'>
      <h2>Selecione os items desejados</h2>
      <% @boxes.each do |box, items| %>
        <%= field_set_tag nil, id: "box_#{box.id}_items", class: 'item-option items-fieldset' do %>
          <legend style="color: <%= box.color %>">Box <%= box.name %></legend>
          <% items.each do |item| %>
            <div>
              <%= check_box_tag "box_items[#{box.id}][]", 
                                item.id, 
                                session["boxes"] && session["boxes"].has_key?(box.id.to_s) && session["boxes"][box.id.to_s].has_key?("items") && session["boxes"][box.id.to_s]["items"] != nil && session["boxes"][box.id.to_s]["items"].include?(item.id.to_s),
                                id: "box_item_#{item.id}", 
                                data: { box: item.carrefour_box.id, item: item.name }, 
                                disabled: '' %>
              <span class="checkmark" style="color: <%= box.color %>"></span>
              <%= label_tag "box_item_#{item.id}", item.name %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div id='select-category' class="tab" data-new-plan-target='tab'>
      <h2>Carrinho de compras</h2>
      <div data-new-plan-target="selectedOptions">
        <% @carrefour_boxes.each do |box| %>
          <div id="box_<%= box.id %>" data-plan="<%= box.plans %>" class="box-options" >
            <div class='selected-box-infos'>
              <%= cl_image_tag box.icon.key, width: 35, data: { 'color-target': box.color } %>
              <div>
                <div>
                  <h4 style="color: <%= box.color %>;"><%= box.name %></h4>
                  <strong class="box-price"></strong>
                </div>
                <div class="box-tools">
                  <div class='f-column'>
                    <%= label_tag "carrefour_box_category_#{box.id}", 'Tamanho da BOX' %>
                    <%= select_tag "box_size[#{box.id}]", 
                                    options_for_select(box.plans.map { |x| [x[0], x[1]["price"]] }, session["boxes"] && session["boxes"]["#{box.id}"] ? session["boxes"]["#{box.id}"]["size_price"] : nil), 
                                    id: "carrefour_box_category_#{box.id}", 
                                    disabled: session["boxes"] ? !session["boxes"].has_key?(box.id.to_s) : true %>
                  </div>
                  <button type="button" data-action="new-plan#deleteBox" data-box-target="<%= box.id %>" class="trash-btn">
                    <i class="far fa-trash-alt"></i>
                    <span class="visibility-hidden">Excluir box</span>
                  </button>
                </div>
              </div>
            </div>
            <ul style="border-color: <%= box.color %>;">
            </ul>
          </div>
        <% end %>
      </div>
      <div id="plan-delivery-fee">
        <div class="display-address" data-new-plan-target="address">
          <% if user_signed_in? && current_user.main_address %>
            <p>Enviar para:</p>
            <%= render 'addresses/current_address', current_address: @current_address %>
            <div id="address-option-button" class="text-center">
              <%= link_to 'escolher outro endereço', '#', class: '', data: { 'bs-toggle': 'modal', 'bs-target': "#addressChoiceModal" } %>
            </div>
          <% elsif current_user %>
            <%= render 'addresses/current_address', current_address: @current_address %>
            <div id="address-option-button" class="text-center">
              <%= link_to 'Selecionar o endereço de entrega', '#', class: '', data: { 'bs-toggle': 'modal', 'bs-target': "#addressChoiceModal" } %>
            </div>
          <% else %>
            <%= render 'addresses/current_address', current_address: @current_address %>
            <div id="address-option-button" class="text-center">
              <%= link_to 'Selecionar o endereço de entrega', new_user_session_path, data: { 'bs-toggle': 'modal', 'bs-target': '#sessionModal' } %>
            </div>
          <% end %>
        </div>
      </div>

      <div id="plan-values">
        <div id="subtotal">
          <p>Subtotal</p>
          <span>-</span>
        </div>
        <div id="discount" data-boxes-selected="" data-discount="<%= Plan.discount_hash %>">
          <p>Descontos</p>
          <span>-</span>
        </div>
        <div id="delivery-fee" data-new-plan-target="fee">
          <p>Taxa de entrega</p>
          <span>-</span>
        </div>
        <div id="total">
          <p>Total</p>
          <div>
            <span>-</span>
            <span>por mês</span>
          </div>
        </div>
      </div>
    </div>
    <button type='button' data-new-plan-target="nextBtn" data-action='new-plan#nextTab' class="btn-blue-rounded" data-signed-in="<%= user_signed_in? %>">Continuar</button>
  <% end %>
  <%= form_with(url: new_plan_path, html: { class: 'd-flex row row-cols-lg-auto g-3 align-items-center', data: { controller: 'input', remote: 'true', action: 'ajax:success->new-plan#updateDeliveryFee', id: 'form-delivery-fee' } }) do |f| %>
  <% end %>

  <div class="modal" id="addressChoiceModal" tabindex="-1" aria-labelledby="sessionHeaders" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= render 'addresses/address_choice', addresses: @addresses, new_address: @address %>
      </div>
    </div>
  </div>
</div>

app/views/plans/show.html.erb
<div class="container my-box-container">
  <h2 class="text-center mb-3"> Meu Carrinho </h2>
  <% @boxes.each do |box, items| %>
    <div class="mybox-card" style="border: 1px solid <%= box.color %>">
      <div class="row mx-auto mybox-card-header" style="background: rgba(<%= box.color.match(/^#(..)(..)(..)$/).captures.map(&:hex).join(', ') %>, 0.7);">
        <%= link_to carrefour_box_path(box) do %>
          <p><b>BOX <%= box.name %></b></p>
        <% end %>
      </div>
      <p class="text-center py-2" style="color: <%= box.color %>"><%= items.map { |item| item.box_item.name }.join(', ') %></p>
      <div class="mybox-info">
        <p><b>Tamanho:</b></p>
        <p><%= items.first.box_size %></p>
        <p><b>Valor:</b></p>
        <p>R$<%= box.plans[items.first.box_size]['price'].to_s.insert(-3, ',') %></p>
        <p><b>Valor do frete:</b></p>
        <p><%= humanized_money_with_symbol @plan.shipment %></p>
      </div>
    </div>
  <% end %>
  <%= simple_form_for @plan, url: plan_path(@plan.id) do |f| %>
    <div class="mx-auto w-75 fs-6">
      <%= f.input :carrefour_card, as: :boolean, label: 'Pagar com cartão carrefour (frete grátis)', input_html: { onchange:"this.form.submit()", class: 'form-check-input' }, class: 'row d-flex justify-content-center' %>
    </div>
  <% end %>
  <div class="text-center mt-3">
    <%= form_tag orders_path do %>
      <%= hidden_field_tag 'plan_id', @plan.id %>
      <%= submit_tag 'Pagar', class: 'btn-dark-blue' %>
    <% end %>
  </div>
</div>